apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: flaskapp-ingress
spec:
  tls:
  - hosts:
    - flaskapp.23.96.12.108
  rules:
    - host: flaskapp.23.96.12.108
      http:
        paths:
          - path: /
            backend:
              serviceName: flaskapp-service
              servicePort: 5000  