apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: nodeapp-ingress
spec:
  tls:
  - hosts:
    - nodeapp.23.96.12.108.xip.io
    secretName: xipio-tls-cert
  rules:
    - host: nodeapp.23.96.12.108.xip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: nodeapp-service
              servicePort: 8080  